import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import { getDefaultPresetNames } from "../src/main/cppx/config";
import { cleanupLegacyWorkspaceFiles, initProject } from "../src/main/cppx/project";
import { getHostAdapter } from "../src/main/cppx/platform";
import {
  createTempDir,
  createToolchain,
  createLogger,
  generatedRoot,
  normalizeNewlines,
  readFixtureJson,
  readFixtureText,
  readJson,
  readText,
  removeDir,
  writeText
} from "./support/helpers";

function normalizeGeneratedText(value: string): string {
  return normalizeNewlines(value)
    .split("\n")
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0)
    .join("\n");
}

test("initProject generates the current baseline files for the active host", async () => {
  const workspace = await createTempDir("init-project");
  const { logger } = createLogger();
  const hostAdapter = getHostAdapter();
  const defaultPresetNames = getDefaultPresetNames();

  try {
    await initProject(workspace, "sample-app", createToolchain(), logger);
    const configToml = await readText(path.join(workspace, ".cppx", "config.toml"));
    assert.match(configToml, /schema_version = 3/);
    assert.match(configToml, /target_name = "sample-app"/);
    assert.match(configToml, /\[package\]/);

    if (process.platform === "win32") {
      assert.equal(
        normalizeGeneratedText(await readText(path.join(generatedRoot(workspace), "CMakeLists.txt"))),
        normalizeGeneratedText(await readFixtureText("init-mingw", "CMakeLists.txt"))
      );
      assert.deepEqual(
        await readJson(path.join(generatedRoot(workspace), "CMakePresets.json")),
        await readFixtureJson("init-mingw", "CMakePresets.json")
      );
      assert.deepEqual(
        await readJson(path.join(generatedRoot(workspace), "vcpkg.json")),
        await readFixtureJson("init-mingw", "vcpkg.json")
      );
    } else {
      assert.match(configToml, /dependency_backend = "none"/);
      await assert.rejects(() => readText(path.join(generatedRoot(workspace), "vcpkg.json")));
      assert.deepEqual(
        (await readJson<any>(path.join(generatedRoot(workspace), "CMakePresets.json"))).configurePresets.map(
          (preset: any) => preset.name
        ),
        [defaultPresetNames.debug, defaultPresetNames.release]
      );
    }

    await assert.rejects(() => readText(path.join(workspace, ".cppx", "CMakeLists.txt")));
    assert.match(
      await readText(path.join(generatedRoot(workspace), "README.generated.txt")),
      /Generated by cppx/
    );

    assert.match(
      await readText(path.join(workspace, "src", "main.cpp")),
      /sample-app is running via cppx!/
    );
    assert.match(
      await readText(path.join(workspace, ".vscode", "tasks.json")),
      new RegExp(hostAdapter.getBinaryName("sample-app").replace(/\./g, "\\."))
    );
    assert.match(
      await readText(path.join(workspace, ".vscode", "launch.json")),
      new RegExp(hostAdapter.getBinaryName("sample-app").replace(/\./g, "\\."))
    );
    assert.match(
      await readText(path.join(workspace, ".gitignore")),
      /\*\.obj/
    );
  } finally {
    await removeDir(workspace);
  }
});

test("cleanupLegacyWorkspaceFiles removes legacy generated files from the workspace root", async () => {
  const workspace = await createTempDir("cleanup-legacy");
  const { logger } = createLogger();

  try {
    await writeText(path.join(workspace, "CMakeLists.txt"), "legacy");
    await writeText(path.join(workspace, "CMakePresets.json"), "{}");
    await writeText(path.join(workspace, "vcpkg.json"), "{}");
    await writeText(path.join(workspace, ".cppx", "CMakeLists.txt"), "legacy");
    await writeText(path.join(workspace, ".cppx", "CMakePresets.json"), "{}");
    await writeText(path.join(workspace, ".cppx", "vcpkg.json"), "{}");
    await writeText(path.join(workspace, ".cppx", "generated", "old.txt"), "old");

    await cleanupLegacyWorkspaceFiles(workspace, logger);

    await assert.rejects(() => readText(path.join(workspace, "CMakeLists.txt")));
    await assert.rejects(() => readText(path.join(workspace, "CMakePresets.json")));
    await assert.rejects(() => readText(path.join(workspace, "vcpkg.json")));
    await assert.rejects(() => readText(path.join(workspace, ".cppx", "CMakeLists.txt")));
    await assert.rejects(() => readText(path.join(workspace, ".cppx", "CMakePresets.json")));
    await assert.rejects(() => readText(path.join(workspace, ".cppx", "vcpkg.json")));
    await assert.rejects(() => readText(path.join(workspace, ".cppx", "generated", "old.txt")));
  } finally {
    await removeDir(workspace);
  }
});
