import path from "node:path";

export const USER_CONFIG_ROOT = ".cppx";
export const GENERATED_ROOT = path.join("build", ".cppx");
export const LEGACY_GENERATED_ROOT = path.join(USER_CONFIG_ROOT, "generated");
export const GENERATED_NOTICE_FILENAME = "README.generated.txt";
export const VSCODE_GENERATED_ROOT = "${workspaceFolder}/build/.cppx";

export const LEGACY_ROOT_GENERATED_FILES = [
  "CMakeLists.txt",
  "CMakePresets.json",
  "vcpkg.json",
  "conanfile.txt",
  "conan_toolchain.cmake",
  "CMakeUserPresets.json"
];

export const LEGACY_USER_ROOT_GENERATED_FILES = [
  "CMakeLists.txt",
  "CMakePresets.json",
  "vcpkg.json",
  "conanfile.txt",
  "conan_toolchain.cmake",
  "CMakeUserPresets.json",
  GENERATED_NOTICE_FILENAME
];

const GENERATED_FILE_NOTE =
  "Generated by cppx. Edit .cppx/config.toml instead; manual changes may be overwritten.";

export function toPosixPath(value: string): string {
  return value.replace(/\\/g, "/");
}

export function getWorkspaceGeneratedRoot(workspace: string): string {
  return path.join(workspace, GENERATED_ROOT);
}

export function getGeneratedSourceRelativePath(sourceFile: string): string {
  return toPosixPath(path.relative(GENERATED_ROOT, sourceFile));
}

export function createGeneratedTextBanner(commentPrefix = "#"): string {
  return [
    `${commentPrefix} ${GENERATED_FILE_NOTE}`,
    `${commentPrefix} This file lives under build/.cppx because it is tool-owned.`,
    ""
  ].join("\n");
}

export function createGeneratedPresetsVendorMeta(): Record<string, unknown> {
  return {
    cppx: {
      generated: true,
      generatedRoot: "build/.cppx",
      configPath: ".cppx/config.toml",
      note: GENERATED_FILE_NOTE
    }
  };
}

export function createGeneratedRootNotice(): string {
  return `${GENERATED_FILE_NOTE}

Files in this directory are regenerated by cppx.
Project-owned config lives in .cppx/config.toml.
`;
}
